name: Python package

on: [push]

jobs:
  build:
    name: build and distribute
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install pypa/build
        run: python3 -m pip install -U build
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -x
          assets=()
          for asset in dist/*; do
            assets+=("$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          gh release create "$tag_name" "${assets[@]}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}