name: Python package

on: [push]

jobs:
  build:
    name: build and distribute
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install pypa/build
        run: python3 -m pip install -U build
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      
      - name: Create release
        #if: startsWith(github.ref, 'refs/tags/')
        # `set -x` prints commands before execution
        # `"${GITHUB_REF##*/}"` - tag name
        run: |
          set -x
          cd dist
          for asset in *
          do
            gh release delete-asset latest "$asset" -y
          done
          gh release upload latest *
          cd ..
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}